baseURL = "/" # "/" defines the root url as the baseurl
languageCode = "en-us"
title = "SandMerit" # Site's Title.

description = "SandMerit is a reward system for people management" # description of the site. Will be used as the default value for the meta description tag.
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "SandFil" # add your company name
  email = "info@sandfil.com" # email

# Menu items
# "name" defines the text displayed for the link.
# "weight" determines the order of each menu item
# "url" is the directory the menu link will point towards.
[[menu.main]]
    name = "Features"
    weight = 2
    url = "/features/"
[[menu.main]]
    name = "Services"
    weight = 4
    url = "/services/"
[[menu.main]]
    name = "Our Customers"
    weight = 3
    url = "/customers/"
[[menu.main]]
    name = "Events"
    weight = 5
    url = "/events/"
[[menu.main]]
    name = "Partnership"
    weight = 6
    url = "/partner/"
[[menu.main]]
    name = "About Us"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "We're Hiring!"
    weight = 7
    url = "/jobs/"
